[build-system]

requires = [
    "setuptools ~= 62.3",  # Should match setup.cfg
    "setuptools_scm[toml] ~= 6.4"  # Should match setup.py
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
