name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Something causes ivcurves tests to take forever on macos and windows.
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on:  ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          python -m pip --version
          python -m pip install --progress-bar off -e .[demo,dev,docs,test]
          python -m pip install --progress-bar off "ivcurves @ git+https://github.com/cwhanse/ivcurves@7ae47284b23cfff167932b8cccae53c10ebf9bf9"
          python -m pip list
      - name: Check manifest
        run: |
          python -m check_manifest  
      - name: Check formatting
        run: |
          python -m black --check .
      # - name: Lint
      #   run: |
      #     python -m pylint .
      - name: Test
        run: |
          python -m pytest --cov=pvfit --cov-report=html:artifacts/test/htmlcov --junitxml=artifacts/test/junit-results.xml -vv pvfit
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ matrix.python-version }}
          path: artifacts
        if: ${{ always() }}
      - name: Build pure-Python source and wheel disributions
        run: |
          python -m build
      - name: Archive disributions
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.python-version }}
          path: dist
        if: ${{ always() }}
