name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on:  ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          python -m pip --version
          python -m pip install --progress-bar off -e .[demo,dev,docs,test]
          python -m pip list
      - name: Check manifest with check_manifest
        run: |
          python -m check_manifest  
      - name: Check formatting with black
        run: |
          python -m black --check .
      # - name: Lint with pylint
      #   run: |
      #     python -m pylint .
      - name: Test with pytest
        run: |
          python -m pytest --cov=pvfit --cov-report=html:artifacts/test/htmlcov --junitxml=artifacts/test/junit-test-results.xml -vv
          mv artifacts/test artifacts/test-${{ matrix.python-version }}
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report-${{ matrix.python-version }}
          path: htmlcov-${{ matrix.python-version }}
        if: ${{ always() }}
      - name: Archive test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts-${{ matrix.python-version }}
          path: artifacts/test-${{ matrix.python-version }}
        if: ${{ always() }}
      - name: Build pure-Python source and wheel disributions
        run: |
          python -m build
      - name: Archive disributions
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.python-version }}
          path: dist
